name: connectedu_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.3

  dio: ^5.3.3

  path_provider: ^2.1.3

  flutter_otp_text_field: ^1.1.1

  permission_handler: ^11.3.1

  flutter_html: ^3.0.0-beta.2

  open_file: ^3.3.2

  flutter_secure_storage: ^9.0.0

  stomp_dart_client: ^1.0.1

  file_picker: ^8.0.3

  jwt_decoder: ^2.0.1

  equatable: ^2.0.5

  intl: ^0.18.1

  image_picker: ^1.0.4

  cupertino_icons: ^1.0.8

  cached_network_image: ^3.3.1

  share_plus: ^7.2.1

  url_launcher: ^6.2.1

  app_links: ^6.4.1
  flutter_native_splash: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/

flutter_native_splash:
  # Light theme splash
  color: "#FFFFFF"
  image: assets/images/logo1.png

  # Dark theme splash
  color_dark: "#000000"
  image_dark: assets/images/logo2.png

  android_gravity: center
  ios_content_mode: scaleAspectFit
  web_image_mode: contain

  # Android 12+ configuration
  android_12:
    image: assets/images/logo1.png
    image_dark: assets/images/logo2.png
    icon_background_color: "#FFFFFF"